/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.util.ArrayList;
import java.util.HashMap;


/**
 *
 * @author chrisrk192
 */
public class Quiz {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String strings[] = {"i", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i",
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "came", "i", "saw", "i", "left", "i", "came", "came",
            "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i",
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came",
            "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i",
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came",
            "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i",
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came",
            "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i",
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came","came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i",
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came",
            "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i",
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "came", "i", "saw", "i", "left", "i", "came", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "came", "i", "saw", "i", "left", "i", "came", "came", "i", "saw", 
            "i", "left", "i", "came", "came", "i", "saw", "i", "left", "i", 
            "came", "came", "i", "saw", "i", "left", "i", "came", "came", "i", 
            "saw", "i", "left", "i", "came", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "came", "i", "saw", "i", "left", 
            "i", "came", "came", "i", "saw", "i", "left", "i", "came", "came", 
            "i", "saw", "i", "left", "i", "came", "came", "i", "saw", "i", 
            "left", "i", "came", "came", "i", "saw", "i", "left", "i", "came",
            "came", "i", "came", "i", "saw", "i", "left", "i", "came", "came"}; 
            long startTime;
        long endTime;
        long totalTime;
        
        startTime = System.currentTimeMillis();
        printDupes(strings);
        endTime   = System.currentTimeMillis();
        totalTime = endTime - startTime;
        System.out.println(totalTime);
        startTime = System.currentTimeMillis();
        printMYDupes(strings);
        endTime   = System.currentTimeMillis();
        totalTime = endTime - startTime;
        System.out.println(totalTime);
        
    }
    public static void printDupes(String [] strings){
        ArrayList<String> arlist = new ArrayList<String>();
        int c = 0;
        for(int i=0; i < strings.length; i++){
            if(arlist.contains(strings[i])){
                //System.out.println(arlist.get(i));
                c++;
            } else
            arlist.add(strings[i]);
        }
        System.out.println(c);
    }
    
    public static void printMYDupes(String[] strings){
        HashMap<String,String> h = new HashMap<>();
        int c = 0;
        for(int i =0;i<strings.length;i++){
            if(h.containsValue(strings[i]))
               c++;
            else
                h.put(strings[i], strings[i]);
        }
        System.out.println(c);
    }
}
